// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Subscription struct {
	ID          int32
	ServiceName string
	Price       int32
	UserID      uuid.UUID
	StartedAt   time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
