// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/sub": {
            "get": {
                "description": "Get a subscription by ID",
                "produces": [
                    "application/json"
                ],
                "summary": "GetSub",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID (int) of specific subscription",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "put": {
                "description": "Update a subscription",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "PutSub",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of subscription",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Structure of subscription",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/subs.sub"
                        }
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Create a subscription",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "PostSub",
                "parameters": [
                    {
                        "description": "Structure of new subscription",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/subs.sub"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete a subscription",
                "produces": [
                    "application/json"
                ],
                "summary": "DeleteSub",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of subscription",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/subs": {
            "get": {
                "description": "Get all subscriptions",
                "produces": [
                    "application/json"
                ],
                "summary": "GetSubs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID, if need to get all subscriptions of a specific user",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete all subscriptions of specific user",
                "produces": [
                    "application/json"
                ],
                "summary": "DeleteUserSubs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "subs.sub": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "integer"
                },
                "service_name": {
                    "type": "string"
                },
                "start_date": {
                    "$ref": "#/definitions/utils.JSONDate"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "utils.JSONDate": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "User subscriptions API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
